transactions/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

# Views
from apps.users.views import LoginView, LogoutView, ListUsers, NewUser, UpdateUser, UpdatePassword

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', ListUsers.as_view(), name='users'),
    path('new_user/', NewUser.as_view(), name='new_user'),
    path('update_user/<slug:username>', UpdateUser.as_view(), name='update_user'),
    path('update_password/<slug:username>', UpdatePassword.as_view(), name='update_password'),
    path('cards/', include('apps.cards.urls')),
]

apps/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class AppUserManager(BaseUserManager):
    def create_user(self, username, password): # , email):
        """Create user"""
        user = self.model(username=username)
        user.set_password(password)
        # user.email = email
        user.save()
        return user

    def create_superuser(self, username, password): # , email):
        """Create superuser"""
        user = self.create_user(username, password)#, email)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class AppUser(AbstractBaseUser, PermissionsMixin):
    """User model."""
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    first_name = models.CharField(
        verbose_name='First Name',
        max_length=255,
        null=True,
        blank=True
    )
    last_name = models.CharField(
        verbose_name='Last Name',
        max_length=255,
        null=True,
        blank=True
    )

    # email = models.EmailField(
    #     verbose_name='email address',
    #     max_length=255,
    #     unique=True,
    # )

    username = models.CharField(max_length=255, unique=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = AppUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def get_full_name(self):
        """Return the full name for this User."""
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):
        """Return username"""
        return self.username

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['username']
        db_table = 'auth_users'

apps/users/forms.py
# Django
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.utils.translation import ugettext as _

from apps.users.models import AppUser


class UserForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label=_('Name')
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label=_('Lastname')
    )
    username = forms.CharField(
        min_length=5,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label=_('Username')
    )
    password1 = forms.CharField(
        min_length=6,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label=_('Password'),
        help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label=_('Repeat your password')
    )
    is_active = forms.BooleanField(
        label=_('Is Active?'),
        required=False
    )

    class Meta:
        model = AppUser
        fields = ("username",)
        field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update({'autofocus': True})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error('password2', error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_active = self.cleaned_data['is_active']
        if commit:
            user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = AppUser
        fields = (
            'first_name',
            'last_name',
            'is_active'
        )
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UpdatePasswordForm(forms.Form):
    username = forms.CharField(
        min_length=5,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label=_('Username')
    )
    password1 = forms.CharField(
        min_length=6,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}, ),
        label=_('Password'),
        help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label=_('Repeat your password')
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UpdatePasswordForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        password_validation.validate_password(password2, self.user)
        return password2

apps/users/views.py
# Django
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import FormView, RedirectView, ListView, UpdateView

# Models
from apps.users.forms import UserForm, UpdateUserForm, UpdatePasswordForm
from apps.users.models import AppUser


class LoginView(FormView):
    """Login view"""
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = reverse_lazy("dashboard")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    """Logout view"""
    pattern_name = 'login'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class ListUsers(LoginRequiredMixin, ListView):
    """List users"""
    template_name = 'users/list_users.html'
    queryset = AppUser.objects.all()
    context_object_name = 'users'


class NewUser(LoginRequiredMixin, FormView):
    """To create new user"""
    template_name = 'users/user_form.html'
    form_class = UserForm
    success_url = reverse_lazy('users')

    def form_valid(self, form):
        """Form valid"""
        form.save()
        return super(NewUser, self).form_valid(form)


class UpdateUser(LoginRequiredMixin, UpdateView):
    """Edit user view"""
    model = AppUser
    template_name = 'users/user_form.html'
    form_class = UpdateUserForm
    slug_url_kwarg = 'username'
    slug_field = 'username'
    success_url = reverse_lazy('users')

    def get_context_data(self, **kwargs):
        """Context"""
        context = super(UpdateUser, self).get_context_data(**kwargs)
        context['edited_user'] = AppUser.objects.get(username=self.kwargs['username'])
        return context
    
    def form_valid(self, form):
        """Form valid"""
        form.save()
        return super(UpdateUser, self).form_valid(form)


class UpdatePassword(LoginRequiredMixin, FormView):
    """Update password and username view"""
    # model = AppUser
    template_name = 'users/change_password.html'
    form_class = UpdatePasswordForm
    slug_url_kwarg = 'username'
    slug_field = 'username'
    success_url = reverse_lazy('users')
    user = None

    def dispatch(self, request, *args, **kwargs):
        self.user = AppUser.objects.get(username=self.kwargs['username'])
        return super(UpdatePassword, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        """Handle form's kwargs"""
        kwargs = super(UpdatePassword, self).get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def form_valid(self, form):
        """Form valid"""
        user = self.user
        user.username = form.cleaned_data['username']
        user.set_password(form.cleaned_data['password2'])
        user.save()
        return super(UpdatePassword, self).form_valid(form)

apps/templates/users/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
    <ul class="breadcrumb hidden-print">
        <li>
            <a href="{% url 'dashboard' %}">
                {% trans 'Home' %}
            </a>
        </li>
        <li>
            <a href="{% url 'users' %}">
                {% trans 'Users' %}
            </a>
        </li>
    </ul>
{% endblock %}
{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border"></div>
        <div class="box-body">
            <form action="" method="post">
                {% csrf_token %}
                <p>
                    <label for="id_username">{{ form.username.label }}:</label>
                    {{ form.username }}
                    {{ form.username.errors }}
                </p>
                <p>
                    <label for="id_password">{{ form.password1.label }}:</label>
                    {{ form.password1 }}
                    {{ form.password1.errors }}

                    {{ form.password1.help_text|safe }}
                </p>
                <p>
                    <label for="id_password2">{{ form.password2.label }}:</label>
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                </p>

                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="fa fa-save"></i>
                            {% trans 'Save' %}
                        </button>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <a href="{% url 'users' %}" class="btn btn-warning btn-block">
                            <i class="fa fa-arrow-circle-left"></i>
                            {% trans 'Cancel' %}
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/templates/users/list_users.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block breadcrumb %}
<ul class="breadcrumb hidden-print">
    <li>
        <a href="{% url 'dashboard' %}">
            {% trans 'Home' %}
        </a>
    </li>
</ul>
{% endblock %}
{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="pull-right">
                <a href="{% url 'new_user' %}" class="btn btn-primary">
                    <i class="fa fa-user-plus"></i>
                    {% trans 'New user' %}
                </a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="box-body">
            <div class="table-responsive">
                <table class="table table table-striped table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>{% trans '#' %}</th>
                            <th>{% trans 'Username' %}</th>
                            <th>{% trans 'Full name' %}</th>
                            <th>{% trans 'Is active' %}</th>
                            <th class="text-center">{% trans 'Change password' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    <a href="{% url 'update_user' user.username %}" data-toggle="tooltip" title="{% trans 'Edit' %}">
                                        {{ user.username }}
                                    </a>
                                </td>
                                <td>{{ user.get_full_name }}</td>
                                <td>{{ user.is_active|yesno }}</td>
                                <td class="text-center">
                                    <a href="{% url 'update_password' user.username %}"
                                    data-toggle="tooltip" title="Change password">
                                        <i class="fa fa-asterisk"></i>
                                        <i class="fa fa-asterisk"></i>
                                        <i class="fa fa-asterisk"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/users/user_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ul class="breadcrumb hidden-print">
    <li>
        <a href="{% url 'dashboard' %}">
            {% trans 'Home' %}
        </a>
    </li>
    <li>
        <a href="{% url 'users' %}">
            {% trans 'Users' %}
        </a>
    </li>
</ul>
{% endblock %}
{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border"></div>
        <div class="box-body">
            <form action="" method="post">
                {% csrf_token %}
                <p>
                    <label for="id_first_name">{{ form.first_name.label }}:</label>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </p>
                <p>
                    <label for="id_last_name">{{ form.last_name.label }}:</label>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </p>
                {% if not edited_user %}
                    <p>
                        <label for="id_username">{{ form.username.label }}:</label>
                        {{ form.username }}
                        {{ form.username.errors }}
                    </p>
                    <p>
                        <label for="id_password">{{ form.password1.label }}:</label>
                        {{ form.password1 }}
                        {{ form.password1.errors }}

                        {{ form.password1.help_text|safe }}
                    </p>
                    <p>
                        <label for="id_password2">{{ form.password2.label }}:</label>
                        {{ form.password2 }}
                        {{ form.password2.errors }}
                    </p>
                {% endif %}


                <p>
                    <label for="id_is_active">{{ form.is_active.label }}:</label>
                    {{ form.is_active }}
                </p>

                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="fa fa-save"></i>
                            {% trans 'Save' %}
                        </button>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <a href="{% url 'users' %}" class="btn btn-warning btn-block">
                            <i class="fa fa-arrow-circle-left"></i>
                            {% trans 'Cancel' %}
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}